### ISSUE TITLE
ERC reconnect fails after suspend

### ISSUE THREAD

**Issue by shlevy** [sshirokov/ZNC.el#22]
If I suspend my laptop and resume it, ERC tries to reconnect automatically but fails. Running M-x znc-erc again works, but it would be nice if ERC's automatic reconnect worked or at least were disabled if it can't be easily made to work.

**Comment by divansantana** [comment]
Having same issue here. @shlevy did you ever make progress with this or implement a workaround?

**Comment by shlevy** [comment]
It happens less often now. Nothing I intentionally changed, but of course it's many system upgrades later.
