### ISSUE TITLE
Access to help maintain znc.el

### ISSUE THREAD

**Issue by vxcamiloxv** [sshirokov/ZNC.el#35]
I'll like help to maintain this package, I use this every day and I'll like to fix some critical issues, I don't want do a fork and new package in melpa with a different name, Is possible have access to make/merge contribution and help with the review?

**Comment by pbeliveau** [comment]
Did someone try to contact @sshirokov to give you access? I'd love to see some of the 'old' pull requests merged in main.

**Comment by sshirokov** [comment]
Oh, sure! Gimme a minute

**Comment by sshirokov** [comment]
@vxcamiloxv you are now a maintainer, if you chose to accept it.

**Comment by sshirokov** [comment]
Sorry, I've been kind of dead to Open Source for a few years, and this ping brought me back.
